version: '2'
services:
    pickabook-app:
        image: pickabook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pickabook-postgresql:5432/pickabook
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pickabook-postgresql:
        extends:
            file: postgresql.yml
            service: pickabook-postgresql
